### ISSUE TITLE
© breaks build

### ISSUE THREAD

**Issue by IanSeyler** [braceio/tags#1]
I have '©' in my HTML code. Removing the '©' makes the build work again.

Mac OS X 10.9.2
Python 2.7.5

```
MBP-003:website iseyler$ tags build
Building site from '.' into '_site'
Traceback (most recent call last):
  File "/usr/local/bin/tags", line 5, in <module>
    pkg_resources.run_script('brace-tags==1.0.6', 'tags')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 489, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1214, in run_script
    exec script_code in namespace, namespace
  File "/Library/Python/2.7/site-packages/brace_tags-1.0.6-py2.7.egg/EGG-INFO/scripts/tags", line 61, in <module>

  File "build/bdist.macosx-10.9-intel/egg/tags/generator.py", line 48, in build_files
  File "build/bdist.macosx-10.9-intel/egg/tags/generator.py", line 19, in build_file
  File "build/bdist.macosx-10.9-intel/egg/tags/tags.py", line 58, in render
  File "build/bdist.macosx-10.9-intel/egg/tags/templatelang.py", line 221, in parse
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 474: ordinal not in range(128)
```

**Comment by colevscode** [comment]
Fixed, thanks!

**Comment by yangshun** [comment]
How about chinese characters?
